// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pkgs/proto/submission.proto

package pkgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request structure as defined in your Solidity contract
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint64                 `protobuf:"varint,1,opt,name=slotId,proto3" json:"slotId,omitempty"`
	Deadline      uint64                 `protobuf:"varint,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	SnapshotCid   string                 `protobuf:"bytes,3,opt,name=snapshotCid,proto3" json:"snapshotCid,omitempty"`
	EpochId       uint64                 `protobuf:"varint,4,opt,name=epochId,proto3" json:"epochId,omitempty"`
	ProjectId     string                 `protobuf:"bytes,5,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pkgs_proto_submission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_proto_submission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pkgs_proto_submission_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSlotId() uint64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *Request) GetDeadline() uint64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *Request) GetSnapshotCid() string {
	if x != nil {
		return x.SnapshotCid
	}
	return ""
}

func (x *Request) GetEpochId() uint64 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type SnapshotSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Header        string                 `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	DataMarket    string                 `protobuf:"bytes,4,opt,name=dataMarket,proto3" json:"dataMarket,omitempty"`
	NodeVersion   *string                `protobuf:"bytes,5,opt,name=nodeVersion,proto3,oneof" json:"nodeVersion,omitempty"`
	ProtocolState string                 `protobuf:"bytes,6,opt,name=protocolState,proto3" json:"protocolState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotSubmission) Reset() {
	*x = SnapshotSubmission{}
	mi := &file_pkgs_proto_submission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotSubmission) ProtoMessage() {}

func (x *SnapshotSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_proto_submission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotSubmission.ProtoReflect.Descriptor instead.
func (*SnapshotSubmission) Descriptor() ([]byte, []int) {
	return file_pkgs_proto_submission_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotSubmission) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SnapshotSubmission) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SnapshotSubmission) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SnapshotSubmission) GetDataMarket() string {
	if x != nil {
		return x.DataMarket
	}
	return ""
}

func (x *SnapshotSubmission) GetNodeVersion() string {
	if x != nil && x.NodeVersion != nil {
		return *x.NodeVersion
	}
	return ""
}

func (x *SnapshotSubmission) GetProtocolState() string {
	if x != nil {
		return x.ProtocolState
	}
	return ""
}

type SubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionResponse) Reset() {
	*x = SubmissionResponse{}
	mi := &file_pkgs_proto_submission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionResponse) ProtoMessage() {}

func (x *SubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_proto_submission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionResponse.ProtoReflect.Descriptor instead.
func (*SubmissionResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_proto_submission_proto_rawDescGZIP(), []int{2}
}

func (x *SubmissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkgs_proto_submission_proto protoreflect.FileDescriptor

const file_pkgs_proto_submission_proto_rawDesc = "" +
	"\n" +
	"\x1bpkgs/proto/submission.proto\x12\n" +
	"submission\"\x97\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06slotId\x18\x01 \x01(\x04R\x06slotId\x12\x1a\n" +
	"\bdeadline\x18\x02 \x01(\x04R\bdeadline\x12 \n" +
	"\vsnapshotCid\x18\x03 \x01(\tR\vsnapshotCid\x12\x18\n" +
	"\aepochId\x18\x04 \x01(\x04R\aepochId\x12\x1c\n" +
	"\tprojectId\x18\x05 \x01(\tR\tprojectId\"\xf6\x01\n" +
	"\x12SnapshotSubmission\x12-\n" +
	"\arequest\x18\x01 \x01(\v2\x13.submission.RequestR\arequest\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x16\n" +
	"\x06header\x18\x03 \x01(\tR\x06header\x12\x1e\n" +
	"\n" +
	"dataMarket\x18\x04 \x01(\tR\n" +
	"dataMarket\x12%\n" +
	"\vnodeVersion\x18\x05 \x01(\tH\x00R\vnodeVersion\x88\x01\x01\x12$\n" +
	"\rprotocolState\x18\x06 \x01(\tR\rprotocolStateB\x0e\n" +
	"\f_nodeVersion\".\n" +
	"\x12SubmissionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xbc\x01\n" +
	"\n" +
	"Submission\x12\\\n" +
	"\x18SubmitSnapshotSimulation\x12\x1e.submission.SnapshotSubmission\x1a\x1e.submission.SubmissionResponse(\x01\x12P\n" +
	"\x0eSubmitSnapshot\x12\x1e.submission.SnapshotSubmission\x1a\x1e.submission.SubmissionResponseB1Z/github.com/PowerLoom/proto-snapshot-server/pkgsb\x06proto3"

var (
	file_pkgs_proto_submission_proto_rawDescOnce sync.Once
	file_pkgs_proto_submission_proto_rawDescData []byte
)

func file_pkgs_proto_submission_proto_rawDescGZIP() []byte {
	file_pkgs_proto_submission_proto_rawDescOnce.Do(func() {
		file_pkgs_proto_submission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkgs_proto_submission_proto_rawDesc), len(file_pkgs_proto_submission_proto_rawDesc)))
	})
	return file_pkgs_proto_submission_proto_rawDescData
}

var file_pkgs_proto_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkgs_proto_submission_proto_goTypes = []any{
	(*Request)(nil),            // 0: submission.Request
	(*SnapshotSubmission)(nil), // 1: submission.SnapshotSubmission
	(*SubmissionResponse)(nil), // 2: submission.SubmissionResponse
}
var file_pkgs_proto_submission_proto_depIdxs = []int32{
	0, // 0: submission.SnapshotSubmission.request:type_name -> submission.Request
	1, // 1: submission.Submission.SubmitSnapshotSimulation:input_type -> submission.SnapshotSubmission
	1, // 2: submission.Submission.SubmitSnapshot:input_type -> submission.SnapshotSubmission
	2, // 3: submission.Submission.SubmitSnapshotSimulation:output_type -> submission.SubmissionResponse
	2, // 4: submission.Submission.SubmitSnapshot:output_type -> submission.SubmissionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkgs_proto_submission_proto_init() }
func file_pkgs_proto_submission_proto_init() {
	if File_pkgs_proto_submission_proto != nil {
		return
	}
	file_pkgs_proto_submission_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkgs_proto_submission_proto_rawDesc), len(file_pkgs_proto_submission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkgs_proto_submission_proto_goTypes,
		DependencyIndexes: file_pkgs_proto_submission_proto_depIdxs,
		MessageInfos:      file_pkgs_proto_submission_proto_msgTypes,
	}.Build()
	File_pkgs_proto_submission_proto = out.File
	file_pkgs_proto_submission_proto_goTypes = nil
	file_pkgs_proto_submission_proto_depIdxs = nil
}
